/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as PostsAddRouteImport } from './routes/posts/add'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts/$postId/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authRecoverAccountIndexRouteImport } from './routes/(auth)/recover-account/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as UsersUserIdUpdateRouteImport } from './routes/users/$userId/update'
import { Route as PostsPostIdEditRouteImport } from './routes/posts/$postId/edit'

const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsAddRoute = PostsAddRouteImport.update({
  id: '/posts/add',
  path: '/posts/add',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/posts/$postId/',
  path: '/posts/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRecoverAccountIndexRoute = authRecoverAccountIndexRouteImport.update({
  id: '/(auth)/recover-account/',
  path: '/recover-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdUpdateRoute = UsersUserIdUpdateRouteImport.update({
  id: '/users/$userId/update',
  path: '/users/$userId/update',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdEditRoute = PostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/posts/add': typeof PostsAddRoute
  '/users': typeof UsersIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/users/$userId/update': typeof UsersUserIdUpdateRoute
  '/login': typeof authLoginIndexRoute
  '/recover-account': typeof authRecoverAccountIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/posts/add': typeof PostsAddRoute
  '/users': typeof UsersIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/users/$userId/update': typeof UsersUserIdUpdateRoute
  '/login': typeof authLoginIndexRoute
  '/recover-account': typeof authRecoverAccountIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/posts/add': typeof PostsAddRoute
  '/users/': typeof UsersIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/users/$userId/update': typeof UsersUserIdUpdateRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/recover-account/': typeof authRecoverAccountIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/posts/add'
    | '/users'
    | '/posts/$postId/edit'
    | '/users/$userId/update'
    | '/login'
    | '/recover-account'
    | '/register'
    | '/posts/$postId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/posts/add'
    | '/users'
    | '/posts/$postId/edit'
    | '/users/$userId/update'
    | '/login'
    | '/recover-account'
    | '/register'
    | '/posts/$postId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/posts/add'
    | '/users/'
    | '/posts/$postId/edit'
    | '/users/$userId/update'
    | '/(auth)/login/'
    | '/(auth)/recover-account/'
    | '/(auth)/register/'
    | '/posts/$postId/'
    | '/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  PostsAddRoute: typeof PostsAddRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PostsPostIdEditRoute: typeof PostsPostIdEditRoute
  UsersUserIdUpdateRoute: typeof UsersUserIdUpdateRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRecoverAccountIndexRoute: typeof authRecoverAccountIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/add': {
      id: '/posts/add'
      path: '/posts/add'
      fullPath: '/posts/add'
      preLoaderRoute: typeof PostsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/recover-account/': {
      id: '/(auth)/recover-account/'
      path: '/recover-account'
      fullPath: '/recover-account'
      preLoaderRoute: typeof authRecoverAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/update': {
      id: '/users/$userId/update'
      path: '/users/$userId/update'
      fullPath: '/users/$userId/update'
      preLoaderRoute: typeof UsersUserIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/edit': {
      id: '/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof PostsPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  PostsAddRoute: PostsAddRoute,
  UsersIndexRoute: UsersIndexRoute,
  PostsPostIdEditRoute: PostsPostIdEditRoute,
  UsersUserIdUpdateRoute: UsersUserIdUpdateRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authRecoverAccountIndexRoute: authRecoverAccountIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
